export const workspaceMetrics = [
  { label: "New Leads Today", value: "18", hint: "Google SEO + referral are strongest" },
  { label: "Quotes in Progress", value: "26", hint: "8 low-margin quotes need review" },
  { label: "Orders In Transit", value: "41", hint: "12 rail, 19 sea, 10 air" },
  { label: "Projected Gross Profit", value: "$86.4K", hint: "Based on accepted and active jobs" },
];

export const moduleCards = [
  {
    id: "acquisition",
    title: "Acquisition Engine",
    subtitle: "Track sources, assign leads, and run second-touch email follow-up.",
    bullets: [
      "Lead pool with source attribution and dedupe",
      "Campaign and landing-page performance view",
      "Warm-up and reactivation email task queues",
    ],
  },
  {
    id: "quotes",
    title: "Quotation Center",
    subtitle: "Standardize rail, sea, and air pricing with visible gross margin.",
    bullets: [
      "Rate-sheet driven quote generation",
      "Manual overrides with margin warnings",
      "Quote-to-order conversion workflow",
    ],
  },
  {
    id: "orders",
    title: "Order Control Tower",
    subtitle: "Manage FCL, LCL, and air jobs from booking to POD.",
    bullets: [
      "Execution milestones and exception queue",
      "Customer, sales, and ops ownership model",
      "Linked cost, receivable, and payable views",
    ],
  },
  {
    id: "finance",
    title: "Cost & Settlement",
    subtitle: "Keep quoted profit, actual cost, and payment status on the same chain.",
    bullets: [
      "Estimated vs actual cost variance tracking",
      "Receivables, payables, and payment registration",
      "Profit views by customer, route, and source",
    ],
  },
];

export const quickWins = [
  "Connect website forms to the new lead schema",
  "Replace static quote simulator with pricing API calls",
  "Move order cost recording into structured payable workflows",
];

export const deliveryPlan = [
  { phase: "Sprint 1", focus: "Lead pool, customer conversion, API skeleton" },
  { phase: "Sprint 2", focus: "Quote workspace, margin summary, convert to order" },
  { phase: "Sprint 3", focus: "Order detail, cost recording, receivable/payable lists" },
];

export const priceManagementModules = [
  {
    id: "fcl_rail_cost",
    title: "整箱铁路供应商成本",
    scope: "POL/POD、箱型箱量、班列日期、运费标识、有效期、维护人、平台汇率",
    quoteRole: "作为整箱报价的主运费成本底座，销售卖价可按毛利规则叠加。",
  },
  {
    id: "fcl_rail_sell",
    title: "整箱铁路销售卖价",
    scope: "出口/进口、箱型、线路类型、是否上架、有效期、卖价备注",
    quoteRole: "销售直接取卖价时仍保留供应商成本快照，用于毛利校验。",
  },
  {
    id: "lcl_freight",
    title: "拼箱运费",
    scope: "装箱港口、运费类型、价格/CBM、文件费、币种、班期、有效期",
    quoteRole: "拼箱报价按 CBM、最低收费和文件费自动拆费用项。",
  },
  {
    id: "fcl_trailer",
    title: "整箱拖车/内贸铁路/水铁联运",
    scope: "提箱地、装箱地、目的地、单柜重量、时效、失效日期、备注",
    quoteRole: "EXW/DDP 场景自动补国内段成本，超重或多区域报价需提示复核。",
  },
  {
    id: "lcl_line",
    title: "拼箱干线物流",
    scope: "起运站、目的城市、价格/T、价格/CBM、送货费、轻货/重货卖价",
    quoteRole: "支持轻重货价格分流，按计费吨/CBM切换核算方式。",
  },
  {
    id: "delivery_oversea",
    title: "欧洲/境外配送价格",
    scope: "配送国家、城市、提货/派送类型、有效期、成本/卖价、供应商",
    quoteRole: "DDP/DDU 末端派送自动带入报价，并在订单阶段回写实际成本。",
  },
];

export const referenceOrderRows = [
  {
    order_no: "LOCAL-ORDER-DRAFT",
    customer: "手工录单客户",
    order_date: "2026-05-28",
    pol: "NINGBO",
    pod: "HAMBURG",
    etd: "待定",
    pieces_weight_volume: "待录入",
    container_qty: "1 x 40HQ",
    order_type: "出口 整箱",
    order_status: "草稿",
    customs_status: "待确认",
    receivable_status: "未生成",
    release_status: "未申请",
    quote_no: "手工录单",
    external_allocation: "否",
    owner: "未分配",
    train_no: "-",
  },
];

export const orderDetailBlueprint = [
  {
    tab: "概况",
    focus: "经营总览",
    blocks: [
      "任务流程：前段、报关、在途、到站等节点按进行中/未开始/完成展示",
      "财务信息：提单、控货、草单、运费/杂费是否结清和未结款项",
      "风险预警：异常开关、异常新增、只看打开",
      "运踪详情：箱号/班列轨迹地图",
      "营收情况：应收、应付、毛利、毛利率、回款和成本利润分析",
      "操作日志：新增、受理、字段修改全留痕",
    ],
  },
  {
    tab: "基本信息",
    focus: "录单主数据",
    blocks: [
      "基础信息：订单号、订单类型、进出口、外配、客户、销售、客服组、付款方式、托书",
      "收发通：发货人、收货人、通知人、预报接收邮箱",
      "货物信息：中文/英文品名、HSCode、唛头、包装、件数、重量、体积、尺寸、货值",
      "路线与服务：CFS-CFS、班列号、订舱方、起运港、目的港、仓位箱号",
      "报关信息：报关状态、方式、报关行、资料截止、附件",
      "国内物流/尾程：入仓、装箱仓、拆箱代理、客户自提/派送",
    ],
  },
  {
    tab: "单证与附件",
    focus: "文件中心",
    blocks: [
      "按附件类型分区：托书、报关资料、提单、账单、发票、其它附件",
      "每个附件需要记录文件名、上传人、上传时间、所属节点和可见范围",
      "客户可见与内部可见要分开，避免敏感成本或备注外露",
    ],
  },
  {
    tab: "费用明细",
    focus: "财务核算",
    blocks: [
      "应收表：客户、费项、单价、数量、分摊、汇率、计费方式、税率、含税总价、币种、已收、账单、发票、推送用友",
      "应付表：供应商、费项、单价、数量、分摊、汇率、计费方式、税率、含税总价、币种、已付、发票、推送用友",
      "营收统计：回款情况、成本利润分析、财务汇率",
    ],
  },
];

export const leadPoolRecords = [
  {
    id: "lead-001",
    lead_no: "LD202605270001",
    company_name: "Nordic Retail GmbH",
    contact_name: "Tom Becker",
    email: "tom@nordic-retail.de",
    phone: "+49 152 3445 9902",
    country: "Germany",
    source_type: "google_seo",
    campaign_name: "rail-lcl-germany",
    channel_detail: "route_landing_form:shenzhen-guangzhou-to-germany-door-delivery | first_landing=/routes/shenzhen-guangzhou-to-germany-door-delivery | submit_page=/routes/shenzhen-guangzhou-to-germany-door-delivery | utm_source=google | utm_medium=organic | utm_campaign=germany_door_delivery",
    intent_level: "hot",
    lead_score: 92,
    transport_mode_interest: "rail",
    shipment_type_interest: "LCL",
    origin: "Shenzhen",
    destination: "Hamburg",
    cargo_desc: "consumer electronics",
    volume_cbm: 2.8,
    weight_kg: 640,
    assigned_to: "Benjamin",
    status: "new",
    created_at: "2026-05-27 09:15",
    last_follow_up_at: null,
    message: "Need weekly LCL option with customs and final delivery.",
  },
  {
    id: "lead-002",
    lead_no: "LD202605270002",
    company_name: "Milano Casa SRL",
    contact_name: "Elena Rossi",
    email: "elena@milano-casa.it",
    phone: "+39 334 1122 883",
    country: "Italy",
    source_type: "linkedin_ads",
    campaign_name: "fcl-europe-launch",
    channel_detail: "campaign_link | first_landing=/quote | submit_page=/quote | utm_source=linkedin | utm_medium=paid_social | utm_campaign=fcl-europe-launch",
    intent_level: "warm",
    lead_score: 71,
    transport_mode_interest: "sea",
    shipment_type_interest: "FCL",
    origin: "Ningbo",
    destination: "Genoa",
    cargo_desc: "furniture",
    volume_cbm: 58,
    weight_kg: 12900,
    assigned_to: "Alice",
    status: "contacted",
    created_at: "2026-05-27 10:05",
    last_follow_up_at: "2026-05-27 13:30",
    message: "Looking for 40HQ with DDP option for two monthly sailings.",
  },
  {
    id: "lead-003",
    lead_no: "LD202605270003",
    company_name: "PolTrade Sp. z o.o.",
    contact_name: "Michal Nowak",
    email: "m.nowak@poltrade.pl",
    phone: "+48 604 224 991",
    country: "Poland",
    source_type: "referral",
    campaign_name: "partner-referral",
    channel_detail: "route_landing_form:china-to-poland-warehouse-rail-freight | first_landing=/routes/china-to-poland-warehouse-rail-freight | submit_page=/routes/china-to-poland-warehouse-rail-freight | utm_source=referral | utm_medium=partner | utm_campaign=partner-referral",
    intent_level: "hot",
    lead_score: 88,
    transport_mode_interest: "rail",
    shipment_type_interest: "FCL",
    origin: "Xi'an",
    destination: "Warsaw",
    cargo_desc: "industrial parts",
    volume_cbm: 64,
    weight_kg: 18400,
    assigned_to: "Benjamin",
    status: "quoted",
    created_at: "2026-05-26 16:20",
    last_follow_up_at: "2026-05-27 11:10",
    message: "Customer needs firm transit time and local trucking.",
  },
  {
    id: "lead-004",
    lead_no: "LD202605270004",
    company_name: "Baltic Beauty OU",
    contact_name: "Sofia Saar",
    email: "sofia@balticbeauty.ee",
    phone: "+372 5566 2099",
    country: "Estonia",
    source_type: "website_form",
    campaign_name: "air-urgent-form",
    channel_detail: "homepage_quick_form | first_landing=/ | submit_page=/ | utm_source=website | utm_medium=form | utm_campaign=homepage_quick_form",
    intent_level: "warm",
    lead_score: 66,
    transport_mode_interest: "air",
    shipment_type_interest: "air_cargo",
    origin: "Shanghai",
    destination: "Tallinn",
    cargo_desc: "cosmetics samples",
    volume_cbm: 0.8,
    weight_kg: 120,
    assigned_to: "Chris",
    status: "new",
    created_at: "2026-05-27 12:40",
    last_follow_up_at: null,
    message: "Urgent air shipment for product launch next week.",
  },
  {
    id: "lead-005",
    lead_no: "LD202605270005",
    company_name: "Paris Maison SAS",
    contact_name: "Claire Dubois",
    email: "claire@parismaison.fr",
    phone: "+33 6 21 55 34 88",
    country: "France",
    source_type: "whatsapp",
    campaign_name: "direct-whatsapp",
    channel_detail: "direct_whatsapp | first_landing=/quote | submit_page=/quote | utm_source=whatsapp | utm_medium=direct | utm_campaign=direct-whatsapp",
    intent_level: "cold",
    lead_score: 41,
    transport_mode_interest: "sea",
    shipment_type_interest: "LCL",
    origin: "Qingdao",
    destination: "Le Havre",
    cargo_desc: "decor goods",
    volume_cbm: 1.1,
    weight_kg: 230,
    assigned_to: "Alice",
    status: "nurturing",
    created_at: "2026-05-25 14:05",
    last_follow_up_at: "2026-05-26 18:30",
    message: "Price sensitive. Wants comparison between sea LCL and rail LCL.",
  },
  {
    id: "lead-006",
    lead_no: "LD202605270006",
    company_name: "EuroKitchen BV",
    contact_name: "Jasper de Vries",
    email: "jasper@eurokitchen.nl",
    phone: "+31 6 4477 2190",
    country: "Netherlands",
    source_type: "google_ads",
    campaign_name: "ddp-netherlands",
    channel_detail: "route_index_recommendation_form | first_landing=/routes | submit_page=/routes | utm_source=google | utm_medium=cpc | utm_campaign=ddp-netherlands",
    intent_level: "warm",
    lead_score: 74,
    transport_mode_interest: "rail",
    shipment_type_interest: "LCL",
    origin: "Chengdu",
    destination: "Rotterdam",
    cargo_desc: "kitchen appliances",
    volume_cbm: 4.2,
    weight_kg: 950,
    assigned_to: "Benjamin",
    status: "contacted",
    created_at: "2026-05-27 08:35",
    last_follow_up_at: "2026-05-27 09:20",
    message: "Interested in DDP with weekly departures and customs support.",
  },
];

export const quotePreviewByMode = {
  rail: [
    {
      fee_code: "freight",
      fee_name: "Rail Main Freight",
      qty: 1,
      unit: "shipment",
      unit_price: 520,
      revenue_amount: 640,
      estimated_cost_amount: 520,
      profit_amount: 120,
      profit_margin: 0.1875,
    },
    {
      fee_code: "customs",
      fee_name: "Customs Clearance",
      qty: 1,
      unit: "job",
      unit_price: 55,
      revenue_amount: 90,
      estimated_cost_amount: 55,
      profit_amount: 35,
      profit_margin: 0.3889,
    },
    {
      fee_code: "delivery",
      fee_name: "Final Mile Delivery",
      qty: 1,
      unit: "job",
      unit_price: 180,
      revenue_amount: 260,
      estimated_cost_amount: 180,
      profit_amount: 80,
      profit_margin: 0.3077,
    },
  ],
  sea: [
    {
      fee_code: "ocean_freight",
      fee_name: "Ocean Freight",
      qty: 1,
      unit: "container",
      unit_price: 1480,
      revenue_amount: 1760,
      estimated_cost_amount: 1480,
      profit_amount: 280,
      profit_margin: 0.1591,
    },
    {
      fee_code: "docs",
      fee_name: "Documentation",
      qty: 1,
      unit: "job",
      unit_price: 35,
      revenue_amount: 60,
      estimated_cost_amount: 35,
      profit_amount: 25,
      profit_margin: 0.4167,
    },
    {
      fee_code: "delivery",
      fee_name: "Destination Delivery",
      qty: 1,
      unit: "job",
      unit_price: 320,
      revenue_amount: 420,
      estimated_cost_amount: 320,
      profit_amount: 100,
      profit_margin: 0.2381,
    },
  ],
  air: [
    {
      fee_code: "air_freight",
      fee_name: "Air Freight",
      qty: 120,
      unit: "kg",
      unit_price: 4.8,
      revenue_amount: 720,
      estimated_cost_amount: 576,
      profit_amount: 144,
      profit_margin: 0.2,
    },
    {
      fee_code: "handling",
      fee_name: "Airport Handling",
      qty: 1,
      unit: "job",
      unit_price: 45,
      revenue_amount: 85,
      estimated_cost_amount: 45,
      profit_amount: 40,
      profit_margin: 0.4706,
    },
    {
      fee_code: "delivery",
      fee_name: "Priority Delivery",
      qty: 1,
      unit: "job",
      unit_price: 90,
      revenue_amount: 140,
      estimated_cost_amount: 90,
      profit_amount: 50,
      profit_margin: 0.3571,
    },
  ],
};

export const orderMilestonesByMode = {
  rail: [
    { node: "Booking Confirmed", status: "done", eta: "2026-06-03" },
    { node: "Cargo Received", status: "done", eta: "2026-06-05" },
    { node: "Rail Departure", status: "active", eta: "2026-06-08" },
    { node: "Customs Clearance", status: "pending", eta: "2026-06-18" },
    { node: "Final Delivery", status: "pending", eta: "2026-06-21" },
  ],
  sea: [
    { node: "Booking Confirmed", status: "done", eta: "2026-06-02" },
    { node: "Container Pickup", status: "active", eta: "2026-06-06" },
    { node: "Vessel Departure", status: "pending", eta: "2026-06-10" },
    { node: "Port Arrival", status: "pending", eta: "2026-07-01" },
    { node: "Delivery", status: "pending", eta: "2026-07-05" },
  ],
  air: [
    { node: "Booking Confirmed", status: "done", eta: "2026-06-01" },
    { node: "Airport Handling", status: "done", eta: "2026-06-02" },
    { node: "Flight Departure", status: "active", eta: "2026-06-03" },
    { node: "Arrival Handling", status: "pending", eta: "2026-06-04" },
    { node: "Priority Delivery", status: "pending", eta: "2026-06-05" },
  ],
};